const googleImports = new Map([
    ['*time', 'google/protobuf/timestamp.proto'],
    ['time.', 'google/protobuf/timestamp.proto'],
    ['.time', 'google/protobuf/timestamp.proto'],
    ['Time.', 'google/protobuf/timestamp.proto'],
    ['.Time', 'google/protobuf/timestamp.proto'],
    ['.Timestamp', 'google/protobuf/timestamp.proto'],
    ['*any', 'google/protobuf/any.proto'],
    ['any.', 'google/protobuf/any.proto'],
    ['.Any', 'google/protobuf/any.proto'],
    ['Any', 'google/protobuf/any.proto'],
    ['any', 'google/protobuf/any.proto'],
    ['Descriptor', 'google/protobuf/descriptor.proto'],
    ['descriptor', 'google/protobuf/descriptor.proto'],
    ['.Descriptor', 'google/protobuf/descriptor.proto'],
    ['.descriptor', 'google/protobuf/descriptor.proto'],
    ['Empty', 'google/protobuf/empty.proto'],
    ['empty', 'google/protobuf/empty.proto'],
    ['.Empty', 'google/protobuf/empty.proto'],
    ['.empty', 'google/protobuf/empty.proto'],
    ['Duration', 'google/protobuf/duration.proto'],
    ['duration', 'google/protobuf/duration.proto'],
    ['.Duration', 'google/protobuf/duration.proto'],
    ['.duration', 'google/protobuf/duration.proto'],
    ['Wrappers', 'google/protobuf/wrappers.proto'],
    ['wrappers', 'google/protobuf/wrappers.proto'],
    ['.wrappers', 'google/protobuf/wrappers.proto'],
    ['.Wrappers', 'google/protobuf/wrappers.proto'],
    ['Struct', 'google/protobuf/struct.proto'],
    ['struct', 'google/protobuf/struct.proto'],
    ['.Struct', 'google/protobuf/struct.proto'],
    ['.struct', 'google/protobuf/struct.proto'],
    ['Plugin', 'google/protobuf/compiler/plugin.proto'],
    ['plugin', 'google/protobuf/compiler/plugin.proto'],
    ['.Plugin', 'google/protobuf/compiler/plugin.proto'],
    ['.plugin', 'google/protobuf/compiler/plugin.proto'],
]);

export default googleImports;